release:
  rollme: true
  appVersion: latest

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 10m
    memory: 600Mi
  limits:
    cpu: 1000m
    memory: 1000Mi

image:
  repository: ""
