release:
  rollme: true
  appVersion: latest

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetMemoryUtilizationPercentage: ""
  targetCPUUtilizationPercentage: ""

resources:
  requests:
    cpu: 10m
    memory: 60Mi
  limits:
    cpu: 100m
    memory: 100Mi

image:
  registry: docker.io
  repository: hello-world
  tag: latest

service:
  type: ClusterIP
  port: 8080



