apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-applicationset-values.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-applicationset-values.labels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "demo-applicationset-values.selectorLabels" . | nindent 4 }}
